### ISSUE TITLE
Jobb

### ISSUE THREAD

**Issue by pyrat** [BartJS/bartjs.github.io#2]
Hei! 

Jeg søker på noen som vil jobber med Node.js, ReactJs, Go, Ruby og Php. 450-525k pa. Tror du det bli noen i Bart JS som blir interessert?

Mvh,
Alastair

**Comment by mikaelbr** [comment]
Hei Alastair!

Det er sikkert mange i BartJS som kunne vært interessert i det, og i alle fall som er godt kvalifiserte. Men BartJS som organisasjon prøver å holde seg separert fra rekruttering og ikke være en annonseringsplattform. Vi kommer dessverre ikke til å sende ut e-poster om slik, dele ut e-post adresser, eller annonsere det på et Meetup eller i en Podcast.

**Comment by pyrat** [comment]
Takk for svaret!
